BabitMF/bmf

bmf/hml/include/hmp/dataexport/data_export.h, bmf/hml/py/py_tensor.cpp, bmf/hml/src/dataexport/data_export.cpp
Add support for importing data from other frameworks supporting dlpack. The support is on Python level, an example Python code sample importing pytorch tensor to hmp tensor can be:
```Python
import torch
import bmf.hml.hmp as hmp
t = torch.zeros((720, 1280, 2), dtype=torch.uint8)
ht = hmp.from_dlpack(t)
```
Both `cpu` and `cuda` devices are supported.
=> Add dlpack data import support

bmf/engine/connector/internal/instance_mapping.hpp, bmf/sdk/cpp_sdk/include/bmf/sdk/log_buffer.h
There are some missing STL headers causing undefined symbol for some compiler / STL version.
=> Add missing headers

bmf/python/py_module_sdk.cpp
py::list::append is non-const, but non-mutable lambda's call operator is const, therefore cannot call the non-const method on copy-captured object.
Note: py::list itself is a referencing-count wrapper of the underlying Python object so copy-capture is correct here.
=> Use mutable lambda

bmf/hml/src/kernel/npp/imgproc.cu
The libnpp version of `imgproc.cu` is still using old typenames.
=> Fix npp imgproc

bmf/hml/include/hmp/ffmpeg/ff_helper.h, bmf/hml/src/cuda/cuda_allocator.cpp, bmf/python/py_module_sdk.cpp, bmf/sdk/cpp_sdk/include/bmf/sdk/video_frame.h, bmf/sdk/cpp_sdk/src/video_frame.cpp
- Fix segment fault caused by using an iterator after erasing.
- Fix memory leaks due to incorrect management of framesctx references.
- By default, do not copy `private_data` when copying frames, as it may affect subsequent conversions with AVFrame.
=> Fix segfault memleak GitHub

bmf/hml/include/hmp/ffmpeg/ff_helper.h, bmf/hml/include/hmp/imgproc/image.h, bmf/hml/include/hmp/tensor.h, bmf/hml/py/py_imgproc.cpp, bmf/hml/src/imgproc/image.cpp, bmf/hml/src/kernel/tensor_factory.cpp, bmf/hml/src/kernel/tensor_factory.h, bmf/hml/src/tensor.cpp, bmf/python/py_module_sdk.cpp, bmf/sdk/cpp_sdk/include/bmf/sdk/video_frame.h, bmf/sdk/cpp_sdk/src/video_frame.cpp, bmf/sdk/cpp_sdk/test/test_video_frame.cpp, bmf/test/cuda_frame_encode/copy_frame.py, bmf/test/cuda_frame_encode/test_copy_transcode.py
包含多个plane的hmp::Frame内部使用一个连续的buffer用来存储多个plane tensor. 这个buffer通过storage_tensor这个tensor来管理，可以通过storage_tensor的h2d，d2h操作达到整个hmp::Frame的h2d/d2h目的。
同时保留对hmp::Frame接口的兼容，修改部分接口实现。
=> Yuvalloctor

bmf/python_sdk/utils.py
This was once fixed in #48 but got overwritten in #62.
=> fix bmf.version() again

bmf/hml/include/hmp/imgproc.h, bmf/hml/include/hmp/imgproc/formats.h, bmf/hml/src/imgproc/image.cpp, bmf/hml/src/imgproc/imgproc.cpp, bmf/hml/src/kernel/cpu/imgproc.cpp, bmf/hml/src/kernel/cuda/imgproc.cu, bmf/hml/src/kernel/image_color_cvt.h, bmf/hml/src/kernel/image_iter.h, bmf/hml/src/kernel/imgproc.cpp, bmf/hml/src/kernel/imgproc.h
This PR adds BGR support in bmf.convert. The support is implemented by extending hmp::img::yuv_to_rgb and hmp::img::rgb_to_yuv, so tensor::reformat will also support BGR pixel format.
BGRA is not supported as the user can use hmp.tensor to operate on the alpha channel. If BGRA is indeed needed, we can add it in the future.
A script to test the BGR support can be as follows:
```Python
import bmf.hml.hmp as mp
import numpy as np
from bmf.lib._bmf.sdk import VideoFrame, AudioFrame, BMFAVPacket, MediaDesc, OpaqueDataKey, MediaType, bmf_convert
from bmf.lib._bmf.sdk import Packet
from bmf.lib._bmf import sdk
import torch
H420 = mp.PixelInfo(mp.kPF_YUV420P, mp.kCS_BT709)
vf = VideoFrame(640, 360, pix_info=H420)
vft = [torch.from_dlpack(x) for x in vf.frame().data()]
vft[0][:] = 50
vft[1][:] = …
```
=> Add BGR support in bmf.convert

.codebase/pipelines/ci.yaml, bmf/test/json_param_transfer/CMakeLists.txt, bmf/test/json_param_transfer/cpp_module.cpp, bmf/test/json_param_transfer/cpp_module.h, bmf/test/json_param_transfer/json_param_transfer.py, bmf/test/json_param_transfer/python_module.py
which can be used in many senarios to transfer non-AV data by json
=> Json transfer

bmf/demo/face_detect/facedetect_demo_colab.ipynb, bmf/test/customize_module/bmf_customize_demo_latest.ipynb, bmf/test/sync_mode/bmf_syncmode_cpp.ipynb, bmf/test/sync_mode/bmf_syncmode_go.ipynb
修复 colab 存量问题，统一对齐至最新版本，facedetect demo trt 版本替换为适配 cuda 12.0 的版本
=> Fit colab demos in new env

bmf/demo/controlnet/ReadMe.md, bmf/demo/controlnet/controlnet_module.py, bmf/demo/controlnet/prompt.txt, bmf/demo/controlnet/test_controlnet.py, bmf/demo/controlnet/text_module.py
The controlnet module uses a TensorRT-optimized controlnet implementation.
Currently, the prompt is read from a file by the text_module and passed to the controlnet_module, the graph looks like:
```
decode --> controlnet_module ---> encode
|            ^
|            |
-------> text_module
````
To sync the prompt with the image, the decoder output is also sent to the text_module, once the decoder outputs EOF, the text_module will also generate EOF. However, in the controlnet_module, the propmt_queue is always empty.
To run the pipeline:
```Python
python test_controlnet.py
```
The input image in case you need it:
=> Add controlnet module

.github/workflows/build_docker.yml, build.sh, docker/Dockerfile.cpu, setup.py
=> add bmf cpu Dockerfile

bmf/engine/connector/include/builder.hpp, bmf/engine/connector/src/builder.cpp, bmf/test/push_data_into_graph/test_push_data.cpp
* fix PushData mode name in cpp interface
* implement Graph::Start(bool, bool) in cpp
* add Grpah::Close() and RealGraph::Close() function in cpp
=> Fix bug that push data mode cannot be called by cpp

build.sh, version.sh
The previous build script did not allow for manual specification of the Python version. In this patch, the `BMF_PYTHON_VERSION` variable is used to pre-set `BMF_PYVER`, which defaults to 3 (same as before).
=> Enhance the ability to find the python environment in build.sh

.github/workflows/greetings.yml
An automated comment bot feature that responds to contributors’ first interactions with the repository.
=> add greeting bot

bmf/c_modules/src/ffmpeg_encoder.cpp, bmf/sdk/cpp_sdk/include/bmf/sdk/filter_graph.h
This PR aim to fix [#131 issue](https://github.com/BabitMF/bmf/issues/131) that `‘av_get_default_channel_layout’ was not declared` and `‘AVStream’ {aka ‘struct AVStream’} has no member named ‘codec’` if we compile bmf with ffmpeg 5.x.x
* add <libavutil/channel_layout.h> into filter_graph.h
* deprecate AVStream->codec 
The following is the compilation error log
```bash
In file included from /home/jack/Documents/workspace/fork/bmf/bmf/sdk/cpp_sdk/include/bmf/sdk/simple_filter_graph.h:24,
from /home/jack/Documents/workspace/fork/bmf/bmf/sdk/cpp_sdk/include/bmf/sdk/ffmpeg_helper.h:24,
from /home/jack/Documents/workspace/fork/bmf/bmf/sdk/cpp_sdk/test/test_audio_frame.cpp:19:
/home/jack/Documents/workspace/fork/bmf/bmf/sdk/cpp_sdk/include/bmf/sdk/filter_graph.h: In member function ‘int …
```
=> fix the incompatibility issue of ffmpeg 5.0 and 5.1

.github/workflows/build_wheels.yml, version.sh
1. Fix a problem in version.sh for mac env building
2. upgrade the download-artifact from v3->v4 in build_wheel because v3 has been deprecated
=> Upgrade release pipeline

.gitignore, bmf/engine/connector/include/builder.hpp, bmf/engine/connector/src/builder.cpp, bmf/test/cpp_builder/cpp_transcode.cpp
add AddCallback interface in cpp builder, fix the callback_binding string
update .gitignore for mac developers
fix cpp_transcode callback case through changing the value of bitrate check
=> engine/builder: enable module callback can be called in cpp

bmf/sdk/cpp_sdk/src/trace.cpp
Minor bugfix for register_queue function. In case TraceBuffer needs to be reused, the current behavior skips reusing the very first buffer.
=> TraceLogger bugfix for register_queue

bmf/engine/connector/src/builder.cpp
Porting a syntax error bugfix from BabitMF internal in `bmf/engine/connector/src/builder.cpp`.
=> bugfix for build.cpp syntax error
